print("Enter your name")
name_=input()
print("Enter your SID")
SID=int(input())
print("Enter your department name")
deptname_=input()
print("Enter your CGPA")
cgpa=float(input())
print("Hey,",("\033[1m"+name_+"\033[0m"),"here !")
print("My SID is ",("\033[1m"+str(SID)+"\033[0m") )
print("I am from" ,("\033[1m"+deptname_+"\033[0m"),"department and my CGPA is ",("\033[1m"+str(cgpa)+"\033[0m"))
#to make a string bold use ("\033[1m"+string+"\033[0m"),"here !")